  
spring:
 data:
   mongodb:
     database: ReminderServiceDB
     port: 27017
     host: localhost
server:
 port: 8082



#
#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: chandan
#      password: root
#      database: reminderDb
#      port: 27017
#      host: localhost
#  application:
#    name: reminder-service
#
#server:
#  port: 8081
